import SessionProviders from "@/providers/SessionProviders";
import "./globals.css";
import type { Metadata } from "next";
import { Mulish } from "next/font/google";

const inter = Mulish({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProviders>{children}</SessionProviders>
      </body>
    </html>
  );
}
